version: '3.8'


services:

  postgres-db:
    image: postgres:15.3
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # volumes:
    #   - ./postgres:/var/lib/postgresql/data
    # ports:
    #   - 5432:5432